name: Plot2Dynmap
main: com.empcraft.plot2dynmap.Main
version: 4.1
api-version: "1.14"
depend: [PlotSquared,dynmap]
description: "This plugin adds a marker around claimed PlotSquared plots in the dynmap interface"
author: Empire92
website: https://github.com/IntellectualSites/
